### ISSUE TITLE
Item is not added to inventory

### ISSUE THREAD

**Issue by OzumaMR** [itsHyper/qb-signrobbery#1]
Hello,

There's no errors in console nor live console.
only a print script:qb-signrobbery 116994
No items in inventory

**Comment by itsHyper** [comment]
Did you add the items into your core?

**Comment by OzumaMR** [comment]
@ -70,7 +70,7 @@ RegisterNetEvent("qb-signrobbery:client:DontBlockIntersectionSign", function()
        }, {}, {}, function()
        end, function()
            StopAnimTask(PlayerPedId(), "amb@prop_human_bum_bin@base", "base", 1.0)
            TriggerServerEvent("dontblockintersectionsign:server:additem")
            TriggerServerEvent("qb-signrobbery:server:DontBlockIntersectionSign")
            DeleteEntity(obj)
        end)
    end
@ -106,7 +106,7 @@ CreateThread(function()
        options = {
            {
                type = 'client',
                event = "qb-signrobbery:client:StealSign",
                event = "qb-signrobbery:client:StopSign",
                icon = 'fas fa-user-secret',
                label = 'Steal Sign',
            }

Also you have a copy/paste error in your readme:
THIS:
	["stopsign"] 				     = {["name"] = "stopsign", 				        ["label"] = "Stop Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "stopsign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Stop Sign"},
	["walkingmansign"] 				     = {["name"] = "walkingmansign", 				        ["label"] = "Pedestrian Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "walkingmansign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Pedestrian Sign"},
	["dontblockintersectionsign"] 				     = {["name"] = "dontblockintersectionsign", 				        ["label"] = "Intersection Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "dontblockintersectionsign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Interdect Sign"},
	["uturnsign"] 				     = {["name"] = "uturnsign", 				        ["label"] = "U Turn Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "uturnsign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "U Turn Sign"},	        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "U Turn Sign"},```

SHOULD BE THIS:
	```lua
    ["stopsign"] 				     = {["name"] = "stopsign", 				        ["label"] = "Stop Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "stopsign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Stop Sign"},
	["walkingmansign"] 				     = {["name"] = "walkingmansign", 				        ["label"] = "Pedestrian Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "walkingmansign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Pedestrian Sign"},
	["dontblockintersectionsign"] 				     = {["name"] = "dontblockintersectionsign", 				        ["label"] = "Intersection Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "dontblockintersectionsign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Interdect Sign"},
	["uturnsign"] 				     = {["name"] = "uturnsign", 				        ["label"] = "U Turn Sign", 			        ["weight"] = 1, 		["type"] = "item", 		["image"] = "uturnsign.png", 		        ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "U Turn Sign"},
    ```
